# Generated by Django 4.0.3 on 2022-04-10 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_type', models.CharField(choices=[('r', 'for rent'), ('s', 'for sale')], max_length=1)),
                ('accomodation_type', models.CharField(choices=[('f', 'flat'), ('h', 'house')], max_length=1)),
                ('address', models.CharField(max_length=200)),
                ('rooms', models.IntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('desc', models.TextField()),
                ('image', models.ImageField(blank=True, default='house.png', null=True, upload_to='houses_pics')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
