# Generated by Django 4.0.3 on 2022-04-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_alter_ad_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='accomodation_type',
            field=models.CharField(choices=[('Flat', 'flat'), ('House', 'house')], max_length=5),
        ),
        migrations.AlterField(
            model_name='ad',
            name='ad_type',
            field=models.CharField(choices=[('rent', 'for rent'), ('sale', 'for sale')], max_length=4),
        ),
    ]
